name: Build and Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0" # 你可以根据需要调整 Node.js 版本

      - name: Install pnpm
        uses: pnpm/action-setup-pnpm@v2
        with:
          version: 9.15.0 # 你可以根据需要调整 pnpm 版本

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Zip dist folder
        run: zip -r dist.zip dist

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist.zip
          path: dist.zip
